### ISSUE TITLE
Apply Helm release secrets dynamically

### ISSUE THREAD

**Issue by rodrigobrim** [rstudio/rstudio#10461]
The secrets are declared inside the Pulumi config files, like the Datadog apiKey:

```
aws-package-manager:fluxcd:
  datadog:
    apiKey:
      secure: v1:ZQSJ7PJQjYdVGUkj:NIoAajNSmwwe0wdo8l2JL3twpQikpHqtgZ0swJDnUhi6Ps0zysP5x8UYkPkEGlo1
```

Then the value must be injected into the manifest:

```
...
Transformations: []yaml.Transformation{
	func(manifest map[string]interface{}, opts ...pulumi.ResourceOption) {
		if manifest["spec"] != nil {
			spec := manifest["spec"]
			if spec.(map[string]interface{})["values"] != nil {
				values := spec.(map[string]interface{})["values"]
				if values.(map[string]interface{})["datadog"] != nil {
					datadog := values.(map[string]interface{})["datadog"]
					if datadog.(map[string]interface{})["apiKey"] != nil {
						datadog.(map[string]interface{})["apiKey"] = settings.Datadog.ApiKey
					}
				}
			}
		}
	},
},
...
```

We need a way to do that dynamically, instructing the code where to find and set the key value.
