### ISSUE TITLE
number_sections not working in quarto

### ISSUE THREAD

**Issue by ccheng11** [rstudio/rstudio#11055]
I am working on a .qmd document in VS Code and have the following YAML opening for output: 

```
output:
  bookdown::pdf_document2:
    keep_tex: false     
    number_sections: true
    toc: false
    latex_engine: "xelatex"
    link-citations: true
    reference-section-title: "References"
    includes:
      in_header: "permeable.tex"
```

So the issue is: the number_sections is not working -- all sections and subsections remain unnumbered when I render the PDF output. May I seek any advice? The VS Code and pandoc are all up to date.
