### ISSUE TITLE
YAML highlighting not working properly for hyphenated yaml entries following a multiline entry

### ISSUE THREAD

**Issue by mine-cetinkaya-rundel** [rstudio/rstudio#11171]
### System details

    RStudio Edition : Desktop
    RStudio Version : RStudio 2022.06.0-daily+351 "Spotted Wakerobin" Daily (ab19e471486aa89e6d350db4e93027845e0847f2, 2022-05-03) for macOS Mozilla/5.0 (Macintosh; Intel Mac OS X 12_3_1) AppleWebKit/537.36 (KHTML, like Gecko) QtWebEngine/5.12.10 Chrome/69.0.3497.128 Safari/537.36
    OS Version      : macOS 12.3.1
    R Version       : 4.1.3

### Steps to reproduce the problem

Create a `_quarto.yml` file and add the following fields:

```
project:
  type: book

book:
  title: "test-book"
  author-meta: "Jane Doe"
  date-meta: today
  description-meta: |
    This is the book description.
  page-footer:
    left: |
      Footer on the left.
```

### Describe the problem in detail

If a previous yaml entry is multiline, and the subsequent one has a hyphen in it, the text before the hyphen is not highlighted properly, making it look like it might not be a valid entry. 

<img width="446" alt="Screen Shot 2022-05-10 at 3 23 20 PM" src="https://user-images.githubusercontent.com/5965649/167707755-06487d6c-abf3-456d-8be3-ca75c60aff7c.png">

### Describe the behavior you expected

`page-footer` should all be same color.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
