### ISSUE TITLE
YAML syntax highlighting not recognizing multiline strings

### ISSUE THREAD

**Issue by andrewheiss** [rstudio/rstudio#11436]
### System details

    RStudio Edition : Desktop
    RStudio Version : RStudio 2022.02.3+492 "Prairie Trillium" Release (1db809b8323ba0a87c148d16eb84efe39a8e7785, 2022-05-16)
    OS Version      : macOS 12.4
    R Version       : 4.2.0

### Steps to reproduce the problem

Create an R Markdown file with this content:

```
---
title: "Some title"
abstract: >-
  Lorem ipsum dolor sit amet
---

Consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
```

### Describe the problem in detail

YAML supports multiline strings with [block scalars](https://yaml-multiline.info/), where long strings can be defined following either a `>` or a `|` (with an optional `-` or `+`) at the end of a YAML key.

The syntax highlighter in RStudio incorrectly marks these as errors:

<img width="686" alt="image" src="https://user-images.githubusercontent.com/73663/173877705-ae56c34b-fd53-4bf8-9f71-4060e9d9fa02.png">

### Describe the behavior you expected

YAML keys with block scalars shouldn't be considered errors. This applies to these situations:

```yaml
abstract: >
  Lorem ipsum dolor sit amet

abstract: >-
  Lorem ipsum dolor sit amet

abstract: >+
  Lorem ipsum dolor sit amet

abstract: |
  Lorem ipsum dolor sit amet

abstract: |-
  Lorem ipsum dolor sit amet

abstract: |+
  Lorem ipsum dolor sit amet
```

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
