### ISSUE TITLE
Quarto Render all option missing

### ISSUE THREAD

**Issue by rjake** [rstudio/rstudio#11768]
When I create a quarto doc with multiple formats, the `Render` button only uses the top format in the list. I can use the drop down to pick the specific format I want to render but I always want both to render. Can there be an option for all formats to be updated at the same time?

```yaml
---
title: "multiple formats"
format: 
  revealjs: default
  docx: default
---

## Quarto
```

![image](https://user-images.githubusercontent.com/14003618/184936382-32245142-4fc4-4aeb-8f45-d223236a93c4.png)
