### ISSUE TITLE
CSS highlighting is lost in Visual Editor

### ISSUE THREAD

**Issue by GegznaV** [rstudio/rstudio#12539]
### System details

    RStudio Edition : Desktop [Open Source]
    RStudio Version : 2022.12.0.354
    OS Version      : Windows 10 x64 (build 19045)
    R Version       : R version 4.2.2 (2022-10-31 ucrt)

### Steps to reproduce the problem

1) Use this code in .qmd (and .Rmd) file:

````css
```{css, echo=FALSE}
pre.sourceCode .r {
  border-left: 5px solid #7b97ea;
  border-radius: 0
}
pre.sourceCode .python {
  border-left: 5px solid #CFB53B;
  border-radius: 0
}
```
````

2) Switch between visual and regular modes

### Describe the problem in detail

In visual mode, CSS syntax highlighting is lost:
![image](https://user-images.githubusercontent.com/12725868/211145853-24b0741f-a7f1-44a9-81ca-115aa56fc429.png)

While in regular mode it was OK:
![image](https://user-images.githubusercontent.com/12725868/211145856-0a8319b6-2c89-4c20-a750-35c7a1a271ec.png)

### Describe the behavior you expected

Use CSS syntax highlighting in both modes.
