### ISSUE TITLE
Cannot add citations using Zotero variant

### ISSUE THREAD

**Issue by noahblakesmith** [rstudio/rstudio#13325]
### Background

[Jurism](https://juris-m.github.io/) is a variant of Zotero that allows multilingual citations.

I can add references in MS Word without issue, which leads me to suspect the issue is with RStudio.

### System details
```
RStudio Edition : Desktop
RStudio Version : Version 2023.06.0+421 (2023.06.0+421)
OS Version      : macOS Ventura (M1)
R Version       : R version 4.3.1 (2023-06-16)
```
```
Jurism                   : 6.0.22m3
Better BibTex for Zotero : 6.7.93
```

### Steps to reproduce the problem

1. Edit => Settings => R Markdown => Citations
   * Zotero library: local
   * Zotero data directory: ~/Jurism
   * Check box for "use Better BibTeX for citation keys and BibTeX export"

2. Tools => Project options => R Markdown => Use libraries: My Library

3. Include the following in the YAML chunk of my .Rmd file ([BBT guidance](https://retorque.re/zotero-better-bibtex/exporting/pandoc/)):
```
output:
  html_document:
    number_sections: T
    pandoc_args: ["--lua-filter=zotero.lua"] # See BBT guidance
bibliography: references.bib
link-citations: T
zotero:
  client: jurism # See BBT guidance
```

4. Switch to "visual mode" in RStudio

### Describe the problem in detail

When I navigate to Insert => Citation, the sources in Jurism do not appear.

### Describe the behavior you expected

The sources in Jurism should appear for selection.

- [x] I have read the guide for [submitting good bug reports](™).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
