### ISSUE TITLE
Error creating and rendering quarto documents on Mac M1

### ISSUE THREAD

**Issue by sharon-wang** [rstudio/rstudio#13993]
### System details

    RStudio Edition : Desktop
    RStudio Version : v2023.06, RStudio-2023.12.0-daily-311
    OS Version      : [TBD]
    R Version       : 4.3.2
    Quarto Version. : 1.3.450, 1.4.506

Originally raised by @javentous in #12791.

### Steps to reproduce the problem

- Create a new Quarto Document or Quarto Presentation
    - See "State not recoverable" error

- Click the Render button with the tutorial hello.qmd
    - See the following error
        ```
        quarto script failed: unrecognized architecture
        /Applications/quarto/bin/quarto: line 129: sysctl: command not found
        ```

### Describe the problem in detail

Copied from https://github.com/rstudio/rstudio/issues/12791#issuecomment-1817730519:
> Hello, I am using the latest stable RStudio v2023.06 and daily RStudio-2023.12.0-daily-311, and I tried both Quarto CLI 1.3.450 and the prerelease Quarto CLI 1.4.506. My R version is 4.3.2. I have reinstalled the stable versions multiple times to no avail.
> 
> I still have the "State not recoverable" error when trying create a new Quarto Document or Quarto Presentation.
> 
> Also, when I try to render from RStudio by clicking the button with the tutorial hello.qmd I get the following error:
> 
> `quarto script failed: unrecognized architecture` `/Applications/quarto/bin/quarto: line 129: sysctl: command not found`
> 
> However when running from Terminal I can `quarto render` and `quarto preview` fine.
> 
> I added `/usr/sbin/` to my path as sysctl is in `/usr/sbin/sysctl` which I got from `where sysctl` in my Terminal. I can run sysctl in my Terminal without issue.

Copied from https://github.com/rstudio/rstudio/issues/12791#issuecomment-1820108916:

> I have run the `--install-rosetta` command before, I will go through your recommendations. I have an M1 Pro MacBook.
> 
> 1. Ran `/usr/sbin/softwareupdate --install-rosetta`
>    
>    * No dice, same errors as before
>    * I did get the following in my terminal
>      `❯ /usr/sbin/softwareupdate --install-rosetta --agree-to-license`
>      `By using the agreetolicense option, you are agreeing that you have run this tool with the license only option and have read and agreed to the terms.`
>      `If you do not agree, press CTRL-C and cancel this process immediately.`
>      `2023-11-20 20:54:59.518 softwareupdate[20112:719190] Package Authoring Error: 042-89646: Package reference com.apple.pkg.RosettaUpdateAuto is missing installKBytes attribute`
>      `Install of Rosetta 2 finished successfully`
> 2. Yes, I can't recall the version, it was with Ventura, I believe 8 months to a year ago, I was up-to-date at that time.
> 3. `> R.Version()$platform`
>    `[1] "aarch64-apple-darwin20"`
> 4. `❯ which quarto`
>    `/Applications/quarto/bin/quarto`
> 5. `❯ quarto check`
>    `Quarto 1.4.506`
>    `[✓] Checking versions of quarto binary dependencies...`
>    `      Pandoc version 3.1.9: OK`
>    `      Dart Sass version 1.69.5: OK`
>    `      Deno version 1.37.2: OK`
>    `[✓] Checking versions of quarto dependencies......OK`
>    `[✓] Checking Quarto installation......OK`
>    `      Version: 1.4.506`
>    `      Path: /Applications/quarto/bin`
>    `[✓] Checking tools....................OK`
>    `      TinyTeX: (not installed)`
>    `      Chromium: (not installed)`
>    `[✓] Checking LaTeX....................OK`
>    `      Tex:  (not detected)`
>    `[✓] Checking basic markdown render....OK`
>    `[✓] Checking Python 3 installation....OK`
>    `      Version: 3.11.6`
>    `      Path: /opt/homebrew/opt/python@3.11/bin/python3.11`
>    `      Jupyter: 5.3.1`
>    `      Kernels: python3, ir, bash, sos`
>    `[✓] Checking Jupyter engine render....OK`
>    `[✓] Checking R installation...........OK`
>    `      Version: 4.3.2`
>    `      Path: /Library/Frameworks/R.framework/Resources`
>    `      LibPaths:`
>    `        - /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library`
>    `      knitr: 1.45`
>    `      rmarkdown: 2.25`
>    `[✓] Checking Knitr engine render......OK`
> 
> Also, thanks for the prompt response, appreciate the work you do, big fan of quarto ٩( ๑╹ ꇴ╹)۶

### Describe the behavior you expected

A user should be able to create/render quarto documents on a Mac M1 machine if:
- they have Rosetta installed and they are running a pre-1.4 version of quarto
- they are running a 1.4 release of quarto (whether they have Rosetta installed or not)

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.posit.co/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by sharon-wang** [comment]
Unable to reproduce on my Mac M1 Ventura 13.6.
- R 4.3.2
- Quarto 1.4.510

Versions I've tried:
- 2023.12.0-daily-311
- 2023.12.0-daily-323
- 2023.09.0+463

Note that I also see the "Package Authoring Error" when installing Rosetta, but it doesn't seem to affect my RStudio functionality.

Adding the `qa repro` tag -- could you please try reproducing on Mac M1 Sonoma? I wonder if this has to do with the new MacOS release.

**Comment by kevinushey** [comment]
FWIW, all seems well on my macOS machine; using macOS Sonoma 14.1 (23B74). Things appear to work fine both with the bundled version of Quarto (1.3.450) as well as the latest pre-release (1.4.513).

**Comment by javentous** [comment]
Hello, apologies for the late response. I was running Sonoma at the time. I can share my current details as I still have the issue even after updating RStudio and my macOS versions:
## R

> R version 4.3.2 (2023-10-31) -- "Eye Holes"
> Copyright (C) 2023 The R Foundation for Statistical Computing
> Platform: aarch64-apple-darwin20 (64-bit)

## RStudio (from the About RStudio option)

> Version 2023.12.0+369 (2023.12.0+369)


## macOS

> Chip Apple M1 Pro
> macOS Sonoma 14.2.1

## Quarto
```
❯ quarto --help
Usage:   quarto
Version: 1.4.506
[ omitted the rest... ]
```
---
In RStudio here is the contents of my projects.qmd file
```
---
title: #"Projects"
listing:
  contents: projects
  type: grid
#  categories: true
  sort: "date desc"
---
```
Upon clocking `Render` at the top of the window I get this as output in my `Background Jobs` tab (to the right of the `Terminal` and `Console` tabs)
```
==> quarto preview projects.qmd --to html --no-watch-inputs --no-browse

quarto script failed: unrecognized architecture 
/Applications/quarto/bin/quarto: line 129: sysctl: command not found
```
Running the same command in the `Terminal` yields the following and it is successful
```
❯ quarto preview projects.qmd --to html --no-watch-inputs --no-browse
pandoc 
  to: html
  output-file: projects.html
  standalone: true
  title-prefix: Conjectures&
  section-divs: true
  html-math-method: mathjax
  wrap: none
  default-image-extension: png
  css:
    - styles.css
  
metadata
  document-css: false
  link-citations: true
  date-format: long
  lang: en
  theme: litera
  title: Projects
  listing:
    contents: projects
    type: grid
    sort: date desc
  
Output created: _site/projects.html

Preparing to preview
[1/1] posts/test/index.qmd
success: successfully compiled /private/var/folders/dj/jyjjf5jx1z910n9793vgxzf00000gn/T/svg-convert-e30a45872a53cabb/temp_1.txt to /private/var/folders/dj/jyjjf5jx1z910n9793vgxzf00000gn/T/svg-convert-e30a45872a53cabb/diagram-1.svg in 40.455209ms

Watching files for changes
Browse at http://localhost:6929/projects.html
GET: /projects.html
GET: /projects.html
```
