### ISSUE TITLE
Rstudio server running in docker image rocker/rstudio can't add user

### ISSUE THREAD

**Issue by yuanqingye** [rstudio/rstudio#14468]
### System details
    RStudio Edition : Server
    RStudio Version : 2023.12.0+369
    OS Version      : ubuntu 22.04
    R Version       : 4.3.3

### Steps to reproduce the problem
Using docker to run rstudio server

If I run on my host machine:
docker run --rm -ti -e PASSWORD=password -p 8787:8787 rocker/rstudio
The service succeeded in running, And I get access to the host machine by hostip:8787 login with credential rstudio:password everything works fine.

But since there are more than one people need to use so I have to add user in. I am running:
docker run --rm -ti -p 8787:8787 rocker/rstudio bash
then I am in container bash
I run:
useradd peter
passwd peter
to setup a new user

but when I get access to the service using hostip:8787 The login page shows up but when I login with peter's password,it pop up a window with red words said:could not connect to r session on rstudio server

what happened? In this case could I add user? how?
### Describe the problem in detail
See above

### Describe the behavior you expected
We can add new user and login to use rstudio server

- [ ] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [ ] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.posit.co/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by yuanqingye** [comment]
I got the message, and this may help someone to figure it out:

`ERROR: unable to create new session keyring - errno:1  LOGGED FROM void rstudio::core::system::resetKeyring() src/cpp/core/system/PosixSystem.cpp 2658`

**Comment by astayleraz** [comment]
I could reproduce this with your steps, and the reason is that no home directory was created with `useradd`. If you are in the  container bash you can run something like `adduser --disabled-password --gecos "" peter && echo "peter:peter" | chpasswd` You can adjust this if you do not want peter understandably to be the password.

**Comment by michaelmayer2** [comment]
Alternatively you simply could run `useradd -m peter` instead of just `useradd peter`. The `-m` option will automatically create the home-directory. 

See more options of the `useradd` command via `useradd --help`. 

On a related but **important** note: 

Please be aware that the way you are running `docker`, all files created within the container will be transient. Once the docker container crashes or you stop/terminate the container, information such as home-directory, user accounts etc... are lost. If you want to avoid such a problem, please consider bind mounting external folders into the docker that contain the home-directory. 

While the ideal solution would be to connect your rstudio server to a directory service (LDAP, AD) - for small user numbers this may be overkill. While not ideal but working, you could create the needed users on the physical server/VM where you run your docker container and then bind mount `/etc/passwd`, `/etc/group` and `/etc/shadow` as well as `/home` into the docker container. 

As an example

```
docker run --rm -ti -e PASSWORD=password -p 8787:8787 -v /etc/passwd:/etc/passwd -v /etc/group:/etc/group -v /etc/shadow:/etc/shadow -v /home:/home rocker/rstudio
```

You could use the following `docker-compose.yml` file to achieve this 

```
version: "3.2"

services:
  rstudio: 
    image: rocker/rstudio 
    hostname: rstudio
    privileged: true 
    volumes:
      - type: bind
        source: /etc/passwd
        target: /etc/passwd
        read_only: true
      - type: bind 
        source: /etc/shadow
        target: /etc/shadow
        read_only: true
      - type: bind
        source: /etc/group
        target: /etc/group
        read_only: true
      - type: bind
        source: /home
        target: /home
    ports:
      - "8787:8787"
    environment: 
      PASSWORD: password 
```

whereafter a simple `docker-compose up -d` would spin up this slightly more persistent environment (you can shutdown it via `docker-compose down`)
