### ISSUE TITLE
Cannot render a Quarto document in ARM Windows

### ISSUE THREAD

**Issue by gtritchie** [rstudio/rstudio#15277]
### System details

    RStudio Edition : Desktop
    RStudio Version : 2024.09.0+375
    OS Version      : Windows-11 23H2 22631.4169 (ARM processor)
    R Version       : 4.4.1

### Steps to reproduce the problem

- install R and RStudio on ARM Windows (both are Intel so will be running via emulation)
- start RStudio, create a new Quarto document, and render it

### Describe the problem in detail

- after required packages are installed, get an error in the Background Jobs tab.

```
==> quarto preview test.qmd --to html --no-watch-inputs --no-browse



processing file: test.qmd
                                                                                                            
output file: test.knit.md

Problem with running R found at C:\Program Files (x86)\R\R-4.4.1\bin\x64\Rscript.exe to check environment configurations.
Please check your installation of R.
```

### Describe the behavior you expected

Be able to render Quarto documents on ARM Windows.

- [x] I have read the guide for [submitting good bug reports](https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports).
- [x] I have installed the latest version of RStudio, and confirmed that the issue still persists.
- [x] If I am reporting an RStudio crash, I have included a [diagnostics report](https://support.posit.co/hc/en-us/articles/200321257-Running-a-Diagnostics-Report).
- [x] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

**Comment by mcarammia** [comment]
Same problem. I have a Windows Laptop 7 which comes with Arms. R and RStudio work well. Quarto works but does not render outputs. This issue is going to affect a growing number of users, as more Microsoft Surface devices now come with Snapdragon/Elite processors.

**Comment by gtritchie** [comment]
> This issue is going to affect a growing number of users, as more Microsoft Surface devices now come with Snapdragon/Elite processors.

Yes, this is on our radar. We will be looking into it when we get the bandwidth.

**Comment by aclinick** [comment]
any update on this?  I'm getting the same issue on my surface laptop 7

**Comment by MGehrke** [comment]
Any news or work-around? I run into the same problem with my recently bought surface. Thanks!

**Comment by aclinick** [comment]
I got around this via wsl. Works great https://www.linkedin.com/pulse/running-rstudio-arm-based-windows-pcs-wsl-ftw-andrew-clinick-zcxdc

**Comment by andreslagerlof** [comment]
Yes, me too. I also have a laptop Surface with snapdragon processor. A solution would be most welcome :-)

**Comment by pwinskill** [comment]
I'm also seeing the same issue breaking workflows on a new windows surface laptop with ARM

**Comment by gtritchie** [comment]
Quarto rendering is now working for me on Windows-11 Pro 24H2 (26100.3775), on my ARM PC (actually an ARM VM running on a Mac, which is the only way I have to try this). I tried the same version I originally tested (RStudio 2024.09.0+375 with R 4.4.1/Intel), and also tried some newer versions of RStudio, R, and Quarto, with the same success.

RStudio and R were installed with default settings, onto a clean, fully-updated Windows system. This is exactly the same thing I tried back in October 2024 when I opened this issue.

Given that the same version that failed before is now working, something has (presumably) been improved in the Windows emulation layer. We (Posit) haven't done anything to fix this.

Curious if others can repeat this result. Again, I'm using the latest Windows-11 release (24H2), fully updated.

Be sure you are using x64/Intel install of R itself, not the ARM version (that definitely won't work).

**Comment by mcarammia** [comment]
Thanks. I just tried, and this is not working for me.

I tried to render an html quarto document, with the content included by
default when you open a new quarto document.

I tried with my old configuration (R version 4.4.2 and
RStudio-2024.09.1-394). Since it did not work, I tried to update both (R
version 4.5.0 and RStudio-2024.12.1-563) but it still did not work. I get
the usual error message:

Problem with running R found at C:\Program Files
(x86)\R\R-4.5.0\bin\x64\Rscript.exe to check environment
configurations.
Please check your installation of R.


I have downloaded the default version of R for Windows though (from Download
R-4.5.0 for Windows. The R-project for statistical computing.
<https://cran.r-project.org/bin/windows/base/>), and I am not sure it is
actually the x64/Intel install. Where can I get that?



Il giorno mer 30 apr 2025 alle ore 19:35 Gary Ritchie <
***@***.***> ha scritto:

**Comment by gtritchie** [comment]
The R version on CRAN is x64, you have to hunt to find the experimental ARM release.

Do you have the latest Windows-11 updates?

**Comment by remlapmot** [comment]
I was just randomly interested in this - did you see, since a few weeks that there's a new free GitHub Windows 11 on ARM runner `windows-11-arm`; <https://github.blog/changelog/2025-04-14-windows-arm64-hosted-runners-now-available-in-public-preview/>. Quarto (1.7.29 - which I'm assuming is x86_64 - I installed it using `choco` on the runner) appears to run just fine on that.

Here's an example workflow run as proof <https://github.com/remlapmot/windows-11-arm-quarto-example/actions/runs/14779785891/job/41496010370>

The workflow I used is in this repo: <https://github.com/remlapmot/windows-11-arm-quarto-example>

Here's a shortened version of it (you can uncomment the TinyTeX parts to render pdf output). Note just out of interest in this I install aarch64 R 4.5.0 and RTools45 - that was unnecessary - there is already x86_64 R 4.4.2 and I think RTools44 on the runner - which both seem to run fine under emulation.

```yaml
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  workflow_dispatch:

name: win-11-arm-quarto-test

permissions: write-all

jobs:
  R-CMD-check:
    runs-on: windows-11-arm

    name: windows-11-arm

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

    steps:
      - uses: actions/checkout@v4
      
      - name: Install aarch64 R and RTools for Windows
        run: |
          # Install R aarch64 4.5.0
          $url = "https://www.r-project.org/nosvn/winutf8/aarch64/R-4-signed/R-4.5.0-aarch64.exe"
          Invoke-WebRequest -Uri "$url" -OutFile R-4.5.0-aarch64.exe -UseBasicParsing -UserAgent "NativeHost"
          Start-Process -FilePath R-4.5.0-aarch64.exe -ArgumentList "/install /norestart /verysilent /SUPPRESSMSGBOXES" -NoNewWindow -Wait

          # Install Rtools45-aarch64
          $url = "https://cran.r-project.org/bin/windows/Rtools/rtools45/files/rtools45-aarch64-6536-6492.exe"
          Invoke-WebRequest -Uri "$url" -OutFile rtools45-aarch64-6536-6492.exe -UseBasicParsing -UserAgent "NativeHost"
          Start-Process -FilePath rtools45-aarch64-6536-6492.exe -ArgumentList "/install /norestart /verysilent /SUPPRESSMSGBOXES" -NoNewWindow -Wait
          
          # Add R and Rtool45 binaries to PATH
          $ENV:PATH = "C:\Program Files\R-aarch64\R-4.5.0\bin;C:\rtools45-aarch64\usr\bin;$ENV:PATH"
          
          # Install pandoc
          # choco install pandoc

          # Install Quarto
          choco install quarto

          # Install TinyTeX
          $rscript = "Rscript"
          # $args = "-e", "install.packages(c('tinytex'), repos = 'https://cloud.r-project.org/'); tinytex::install_tinytex(); tinytex::tlmgr_install(c('makeindex', 'upquote', 'inconsolata'))"
          # & $rscript $args

          # Add TinyTeX binaries to PATH
          # $ENV:PATH = "C:\Users\runneradmin\AppData\Roaming\TinyTeX\bin\windows;$ENV:PATH"
          
          # Install knitr and rmarkdown
          $args = "-e", "install.packages(c('knitr', 'rmarkdown'), repos = 'https://cloud.r-project.org/');"
          & $rscript $args
          
          quarto render index.qmd
```

I have no idea if it's possible to test graphical applications on it. But every x86_64 command line tool I've called on it has worked (pandoc, texlive) - so maybe Windows on ARM x86_64 emulation has improved recently (the runner says it uses Microsoft Windows 11, 10.0.22631, Enterprise).

**Comment by gtritchie** [comment]
Thanks for the data.

This issue is specifically for the RStudio IDE's quarto features, and AFAIK it is not possible to connect to Windows-based GitHub Runners using RDP or equivalent (but I haven't really explored if that's the case).

**Comment by gtritchie** [comment]
> Yes, last update is to version 24H2 (KB5055627). What a disappointment.

Yup, since I can no longer repro the issue there's really nothing else I can do.

**Comment by pwinskill** [comment]
I am still replicating the original issue on my windows surface laptop:
```
RStudio Edition : Desktop
RStudio Version : 2025.05.0+496
OS Version      : Windows-11 24H2 26100.3915
Processor       : Snapdragon(R) X 12-core X1E80100 ARM
R Version       : 4.5.0
Quarto version  : 1.7.31
```

Error when rendering quarto to html:
```
==> quarto preview test.qmd --to html --no-watch-inputs --no-browse



processing file: test.qmd
                                                                                                            
output file: test.knit.md

Problem with running R found at C:\Program Files (x86)\R\R-4.5.0\bin\x64\Rscript.exe to check environment configurations.
Please check your installation of R.

```

Output and error when running `quarto check` in the RStudio terminal (if helpful):
```
$ quarto check
Quarto 1.7.31
[>] Checking environment information...
      Quarto cache location: C:\Users\pwinskil\AppData\Local\quarto
[>] Checking versions of quarto binary dependencies...
      Pandoc version 3.6.3: OK
      Dart Sass version 1.85.1: OK
      Deno version 1.46.3: OK
      Typst version 0.13.0: OK
[>] Checking versions of quarto dependencies......OK
[>] Checking Quarto installation......OK
      Version: 1.7.31
      Path: C:\Users\pwinskil\AppData\Local\Apps\Quarto\bin
      CodePage: 1252

[>] Checking tools....................OK
      TinyTeX: (external install)
      Chromium: (not installed)

[>] Checking LaTeX....................OK
      Using: TinyTex
      Path: C:\Users\pwinskil\AppData\Roaming\TinyTeX\bin\windows\
      Version: 2024

[>] Checking Chrome Headless....................OK
      Using: Chrome found on system
      Path: C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe
      Source: Windows Registry

[>] Checking basic markdown render....OK

[>] Checking Python 3 installation....(None)

      Unable to locate an installed version of Python 3.
      Install Python 3 from https://www.python.org/downloads/

[>] Checking R installation...........(None)

R succesfully found at C:\Program Files (x86)\R\R-4.5.0\bin\x64\Rscript.exe.
However, a problem was encountered when checking configurations of packages.
Please check your installation of R.
```

**Comment by Sebaristoteles** [comment]
I can confirm that the issue also exists when using VS Code, suggesting it is not an issue of RStudio.

Windows 11 24H2 KB2267602 (Version 1.429.147.0)
Processor: Snapdragon(R) X 12-core X1E80100 @ 3.40 GHz   3.42 GHz

Checking R installation .... (None)

**Comment by jefunes** [comment]
I had the same issue as @Sebaristoteles.

**Comment by mcarammia** [comment]
Hi, I was wondering if a different approach could be tried. I am having
issues running several other applications as well on my Windows ARMS. I
have solved those issues by installing x64 versions of those applications.
This forces my laptop to use the x64 emulator, which works just great.
Would it be possible to install R, R-Studio, and Quarto versions without
any ARMS support, so that they are run with the emulator? And if so, how?
Thanks



Il giorno mar 10 giu 2025 alle ore 15:44 jefunes ***@***.***>
ha scritto:

**Comment by gtritchie** [comment]
> would it be possible to install R, R-Studio, and Quarto versions without any ARMS support, so that they are run with the emulator?

RStudio and Quarto are built for x64, not ARM (on Windows at least), so they are already using the emulator.

We hope to provide native ARM versions for Windows eventually, but can't say when this will happen (tracked by #11977 for RStudio itself).

**Comment by mcarammia** [comment]
I see. R however does seem to have "experimental support for 64-bit ARM". I
wonder if that is causing the issue. Indeed the rendering error seems to be
with finding R: "Problem with running R found at C:\Program Files
(x86)\R\R-4.5.0\bin\x64\Rscript.exe to check environment configurations.
Please check your installation of R."

Do you think we could try with some R builds that do not include ARMS
support? Or maybe try earlier versions


Il giorno lun 7 lug 2025 alle ore 19:26 Gary Ritchie <
***@***.***> ha scritto:

**Comment by gtritchie** [comment]
> Do you think we could try with some R builds that do not include ARMS

That is what people are already trying.

The ARM build of R does not work with the x64 build of RStudio. You **must** use the x64 build of R with the x64 build of RStudio.

**Comment by gtritchie** [comment]
Issue tracking a Windows ARM build of deno (the runtime used by quarto): https://github.com/denoland/deno/issues/8422

**Comment by brystolbates** [comment]
Any updates or timeline yet on this issue?

**Comment by remlapmot** [comment]
I think that I can show what causes this error - although I cannot fully explain it.

It is not related to running Quarto from within RStudio - so I would say this can be closed in this repo. I will post this explanation in the Quarto repo under an issue there.

This problem is actually a problem of loading certain packages in x86 R on the Windows 11 on ARM x86 emulation under Quarto's knitr engine.

The problem is as follows. There seem to be a (from what I can tell small) number of packages when if you load them in an x86 R session that cause the R session to exit with a non-zero exit code - I see exit code 127.

In my testing the problem occurs for the following packages (but I guess there might be more - and indeed I haven't tried to work out if even 3 of these 4 are say caused by 1 common dependency)

- rmarkdown
- htmltools
- cli
- rlang

To see what I see simply run in a Git Bash shell on your Windows 11 on ARM machine (where Rscript is from an x86 installation):

```sh
Rscript -e "install.packages('rmarkdown', repos = 'https://cloud.r-project.org/', type = 'binary'); require('rmarkdown')"
echo $?
```

And you'll see - the key being the 127 instead of a 0.

```
Loading required package: rmarkdown
Warning message:
package 'rmarkdown' was built under R version 4.4.3 
127
```

Or install Quarto and run its knitr capabilities script - which loads rmarkdown via the line `requireNamespace('rmarkdown', quietly = TRUE)`, 
<https://github.com/quarto-dev/quarto-cli/blob/a6507eeb172c0a09e2a059425d1f994db12b4bfb/src/resources/capabilities/knitr.R#L20>

```sh
Rscript /c/ProgramData/Chocolatey/lib/quarto/tools/share/capabilities/knitr.R
echo $?
```

And you should see the 127 exit code again.

```
--- YAML_START ---
versionMajor: 4 
versionMinor: 4 
versionPatch: 2 
home: C:/PROGRA~2/R/R-44~1.2 
libPaths:
  - "C:/Program Files (x86)/R/R-4.4.2/library" 
packages:
  knitr: "1.50"
  rmarkdown: "2.29"
--- YAML_END ---
127
```

Or run this within Quarto's `quarto check`

```sh
quarto check knitr --log-level=debug
```

And you should see.

```
Quarto version: 1.8.24
Quarto 1.8.24
-- Searching for R binary --
Looking for 'Rscript' in QUARTO_R: undefined
Looking for 'Rscript' in R_HOME: undefined
Looking for 'Rscript' in PATH.
[execProcess] CMD /C where Rscript

(|) Checking R installation...........[execProcess] Success: true, code: 0
Found in PATH at C:\Program Files (x86)\R\R-4.4.2\bin\x64\Rscript.exe
[execProcess] C:\Program Files (x86)\R\R-4.4.2\bin\x64\Rscript.exe --version
[execProcess] Success: true, code: 0

++R found at C:\Program Files (x86)\R\R-4.4.2\bin\x64\Rscript.exe is working.
-- Checking knitr engine capabilities --
[execProcess] C:\Program Files (x86)\R\R-4.4.2\bin\x64\Rscript.exe C:\ProgramData\Chocolatey\lib\quarto\tools\share\capabilities\knitr.R
[execProcess] Success: false, code: -1073741569

++ Problem with results of knitr capabilities check.
    Return Code: -1073741569 (success is false)
    with stdout from R:
--- YAML_START ---
versionMajor: 4 
versionMinor: 4 
versionPatch: 2 
home: C:/PROGRA~2/R/R-44~1.2 
libPaths:
  - "C:/Program Files (x86)/R/R-4.4.2/library" 
packages:
  knitr: "1.50"
  rmarkdown: "2.29"
--- YAML_END ---


[>] Checking R installation...........(None)

R succesfully found at C:\Program Files (x86)\R\R-4.4.2\bin\x64\Rscript.exe.
However, a problem was encountered when checking configurations of packages.
Please check your installation of R.

[NotebookContext]: Starting Cleanup
```

Althought the exit code from this whole process is 0, this is because Quarto has captured the non-zero exit code from running its knitr capabilities R script. For some reason Quarto turns Rscript's exit code of 127 into its own (exit) code of -1073741569 (I don't know why it doesn't say 127 instead).

Here is a GitHub Actions workflow run which demonstrates all this

<https://github.com/remlapmot/windows-11-arm-quarto-example/actions/runs/17949943645/job/51046164706>

The non-zero Rscript exit codes from these R sessions cause Quarto's knitr engine to error because I think it loads rmarkdown and maybe htmltools in R sessions when running its knitr engine. And I guess all its R sessions must exit with 0 exit codes from its overall `quarto render` to complete successfully.

I don't understand what it is in these packages which cause the non-zero exit code - maybe there is some compiled machine code which the emulation can't run or something like that. I am certainly interested in anyone can work this out.

Or indeed let me know you think if I am wrong about this.
