### ISSUE TITLE
Add editor font support to RStudio Server

### ISSUE THREAD

**Issue by statkclee** [rstudio/rstudio#2534]
### System details

    RStudio Edition : 
    RStudio Version : 1.1.442
    OS Version      :  Ubuntu 16.04
    R Version       :  3.4.4 (2018-03-15)

### Steps to reproduce the problem
Select menu from Tools -> Global Options -> Appearance

### Describe the problem in detail

There is no "Editor Font" dropdown UI.
The default font is not adequate as the main CJK editor font.

### Describe the behavior you expected

It should show "Editor Font" dropdown UI just like RStudio Desktop version.

![image](https://user-images.githubusercontent.com/5325425/38072571-e90e2992-3361-11e8-894d-d5cfe3508044.png)

**Comment by jmcphers** [comment]
The reason there isn't an Editor Font dropdown in RStudio Server is that web applications don't get to ask your system for a list of installed fonts. A further complication is that you can connect to RStudio Server from several different computers with different sets of fonts, so the font you chose on one system might not be available on another one.

We might be able to offer a font selection experience of some kind, such as (a) testing against a large list of known monospace fonts, (b) providing a free-form font name entry box, and/or (c) providing a place to upload a monospace web font of your choice, but it is not possible to fully replicate the desktop experience.

Appreciate the suggestion!

**Comment by statkclee** [comment]
How about embedding one Korean coding fonts?
From my experience so far, there are a few Korean coding font. One of them is Naver D2 Coding font.

- https://github.com/naver/d2codingfont

Such that instead of supporting all the customized fonts for R Coding, only one coding font for each country will be sufficient enough.

**Comment by balwierz** [comment]
What about having a free-form _preferred_ font name(s)?
Rstudio server could try using them and if not available use the default font.

I am using fira-code fonts for nice ligatures for <- != >= && and so on. When I force firefox to use it as a sheriff-less font, it does not apply ligatures. (Rstudio desktop does.)

**Comment by jmcphers** [comment]
See also https://github.com/rstudio/rstudio/issues/4134 (Use embedded webfonts for primary UI and fixed width fonts)

**Comment by loudermilk** [comment]
Would make my RStudio experience better to be able to use Fira Code ligatures - https://github.com/tonsky/FiraCode

**Comment by jiho** [comment]
What about choosing from web font services (e.g. Google Fonts)?

**Comment by Gabryxx7** [comment]
Hi everyone! I have RStudio-Server installed on my own server and I decided to style it up a little bit with custom themes and fonts. I came across this issue and I decided to give my own solution which works rather well and it's extremely easy (I am gonna use Fire Code for the example @loudermilk, but it would work with google fonts as well @jiho or whatever server) :

1. (actually optional but some people might prefer it) Download Fira Code and put it somewhere accessible from the internet (your github.io page, your own server, or even just a link to dropbox, or  even google drive or google font, as long as it's a direct link to the file!). I have it on my own server, in the same folder from where my websites gets css/js files, so accessing `http://test.com/fonts/Fira/ttf/FiraCode-Light.ttf` would download the .ttf file. But for this example I will get the files raw from the Fira Code GitHub repository:`https://github.com/tonsky/FiraCode/raw/master/distr/ttf/FiraCode-Light.ttf`
1. Find a way to apply custom CSS, I am using the "User JavaScript and CSS" extension for Chrome
2. Download Fira Code from GitHub, and open the .css file that comes with it with any editor (I use Visual Studio Code)
3. Modify the urls so that point to your Fira folder on the server: I ran a simple find and replace, I looked for `url('` and replaced with `url('https://github.com/tonsky/FiraCode/raw/master/distr/`.
4. Edit your Chrome custom CSS (the extension I use allows me to specify different CSS or even JS code for different domains) and add one last rule so that the final CSS loaded everytime a page on the domain is opened would look something like"

```css
@font-face{
    font-family: 'Fira Code';
    src: url('https://github.com/tonsky/FiraCode/raw/master/distr/eot/FiraCode-Light.eot');
    src: url('https://github.com/tonsky/FiraCode/raw/master/distr/eot/FiraCode-Light.eot') format('embedded-opentype'),
         url('https://github.com/tonsky/FiraCode/raw/master/distr/woff2/FiraCode-Light.woff2') format('woff2'),
         url('https://github.com/tonsky/FiraCode/raw/master/distr/woff/FiraCode-Light.woff') format('woff'),
         url('https://github.com/tonsky/FiraCode/raw/master/distr/ttf/FiraCode-Light.ttf') format('truetype');
    font-weight: 300;
    font-style: normal;
}

@font-face{
    font-family: 'Fira Code';
    src: url('https://github.com/tonsky/FiraCode/raw/master/distr/eot/FiraCode-Regular.eot');
    src: url('https://github.com/tonsky/FiraCode/raw/master/distr/eot/FiraCode-Regular.eot') format('embedded-opentype'),
         url('https://github.com/tonsky/FiraCode/raw/master/distr/woff2/FiraCode-Regular.woff2') format('woff2'),
         url('https://github.com/tonsky/FiraCode/raw/master/distr/woff/FiraCode-Regular.woff') format('woff'),
         url('https://github.com/tonsky/FiraCode/raw/master/distr/ttf/FiraCode-Regular.ttf') format('truetype');
    font-weight: 400;
    font-style: normal;
}

@font-face{
    font-family: 'Fira Code';
    src: url('https://github.com/tonsky/FiraCode/raw/master/distr/eot/FiraCode-Medium.eot');
    src: url('https://github.com/tonsky/FiraCode/raw/master/distr/eot/FiraCode-Medium.eot') format('embedded-opentype'),
         url('https://github.com/tonsky/FiraCode/raw/master/distr/woff2/FiraCode-Medium.woff2') format('woff2'),
         url('https://github.com/tonsky/FiraCode/raw/master/distr/woff/FiraCode-Medium.woff') format('woff'),
         url('https://github.com/tonsky/FiraCode/raw/master/distr/ttf/FiraCode-Medium.ttf') format('truetype');
    font-weight: 500;
    font-style: normal;
}

@font-face{
    font-family: 'Fira Code';
    src: url('https://github.com/tonsky/FiraCode/raw/master/distr/eot/FiraCode-Bold.eot');
    src: url('https://github.com/tonsky/FiraCode/raw/master/distr/eot/FiraCode-Bold.eot') format('embedded-opentype'),
         url('https://github.com/tonsky/FiraCode/raw/master/distr/woff2/FiraCode-Bold.woff2') format('woff2'),
         url('https://github.com/tonsky/FiraCode/raw/master/distr/woff/FiraCode-Bold.woff') format('woff'),
         url('https://github.com/tonsky/FiraCode/raw/master/distr/ttf/FiraCode-Bold.ttf') format('truetype');
    font-weight: 700;
    font-style: normal;
}

.ace_layer.ace_text-layer {
    font-family: 'Fira Code' !important;
}
```
Et voilà! Chrome, the extension and CSS will take care of downloading the CSS and all the required fonts files and apply the new CSS to the pages of the domain!

Proof of working Fira Code on RStudio-Server

![Screen Shot 2019-04-25 at 6 25 08 pm](https://user-images.githubusercontent.com/6282055/56721084-7c969500-6787-11e9-8051-8868f7ed12fd.png)

One could also edit the Rstudio-Server main PHP/HTML file (not sure what language is used), and add a line on top to include the custom css with your fonts, this would be a pretty good solution, but it wouldn't allow different users to have different fonts.

*TL;DR Download che Chrome extension "User JavaScript and CSS" and just open your rstudio-server on chrome, copy-paste the above CSS code and save*

**Comment by taiyodayo** [comment]
Thank you Gabriele san, it is plain fantastic!!
Never thought it could be achieved so elegantly.
R coders in my team is forever thankful for your suggestion!

**Comment by antoine-sachet** [comment]
The CSS given by @Gabryxx7 is now broken (`/eot` folder has been removed) but in any case, Fira Code is now available via the `jsdelivr` CDN (see [README](https://github.com/tonsky/FiraCode#browser-support).

So the CSS can simply be:
```css
@import url(https://cdn.jsdelivr.net/gh/tonsky/FiraCode@1.206/distr/fira_code.css);

.ace_layer.ace_text-layer {
    font-family: 'Fira Code' !important;
}
```

**Comment by Gabryxx7** [comment]
You could actually store the FiraCode files in your own server and use the URL in your CSS, you would have to update it yourself, but if you have `git` in your server you can just refer to the repository folder on your server.

**Comment by y1zhou** [comment]
> However there is an issue with the cursor position. It does not fall between letters and does not reach the end of the line, so it is pretty unusable.

@antoine-sachet This was the case when I changed the font to Fira Code Retina. My solution was declaring the font size in the custom CSS:

```css
.ace_layer.ace_text-layer {
        font-size: 13px !important;
        font-family: 'Fira Code Retina', monospace !important;
    }
}
```

You may have to play with the values. `Tools - Global options - Appeariance - Editor font size` is 10 in my settings.

**Comment by eliocamp** [comment]
Can confirm that @antoine-sachet fix was unusable for me. :(

**Comment by antoine-sachet** [comment]
@eliocamp The solution from @y1zhou worked for me. My font size is 11 and with my screen resolution `12.7px` is perfect.

```CSS
@import url('https://fonts.googleapis.com/css?family=Fira+Code');

.ace_layer.ace_text-layer {
    font-family: 'Fira Code Retina', monospace !important;
    font-size: 12.7px !important;
}
```
