### ISSUE TITLE
Add stable CSS class names for themeable elements

### ISSUE THREAD

**Issue by randy3k** [rstudio/rstudio#3368]
### System details

    RStudio Edition : Desktop
    RStudio Version : current master
    OS Version      : 10.13.4
    R Version       : 3.5.1

<img width="1112" alt="screen shot 2018-08-24 at 2 58 45 am" src="https://user-images.githubusercontent.com/1690993/44601535-c23f3000-a7aa-11e8-834b-7176b96d4036.png">

I have been working on customizing the theme of RStudio via a custom [rstheme](https://github.com/randy3k/dotfiles/blob/master/.R/rstudio/themes/Wombat.rstheme). In there, I have to override the style for a number of UI classes. For example,
```css
/* pane toolbar */
.GOLWFGSBG-B, .GOLWFGSBJAC, .GOLWFGSBEV {
     background: #404040 !important;
}
/* popup */
.rstudio-themes-flat.rstudio-themes-dark-menus .GOLWFGSBI1 .popupMiddleCenter {
     background: #404040 !important;
}
```
The UI items do not have proper names and have only the generated names (they are generated by gwt!?). The random generated names make theming RStudio hard and the resulting theme may not be as well portable.
