### ISSUE TITLE
Vagrantfile fails to up due to missing cmake

### ISSUE THREAD

**Issue by chrisvoncsefalvay** [rstudio/rstudio#4712]
When executing `vagrant up`, the operation fails due to `cmake` not being available (also, it appears the Vim version is incorrect for YCM).

```
    primary:
    primary: Done!
    primary:
    primary: YouCompleteMe unavailable: requires Vim 7.4.1578+.
    primary: ERROR: Unable to find executable 'cmake'. CMake is required to build ycmd
    primary: /rstudio/vagrant/provision-primary-user.sh: line 33: cmake: command not found
```
