### ISSUE TITLE
Manually deselected index.Rmd produces warnings on deploy to shinyapps.io

### ISSUE THREAD

**Issue by alandipert** [rstudio/rstudio#4743]
### System details

    RStudio Edition : Desktop
    RStudio Version : 1.2.1335
    OS Version      : macOS 10.14.4
    R Version       : 3.5.2

### Steps to reproduce the problem

> Originally reported at rstudio/shiny#1561, I was able to reproduce today

* Create a new Shiny app project
* Add the following `index.Rmd` to the project directory:
```
# index.Rmd
---
title: "Readme"
author: "Foobar"
output: 
  html_document:
    css: [../../../gh-pages_global/gh-pages_navbar.css, ../../../gh-pages_global/custom-width.css]
    includes:
      in_header: ../../../gh-pages_global/_navbar.html
---
I'm a very thorough documentation for this shiny app
```
* Deploy to shinyapps.io and deselect `index.Rmd` in the "Publish to Server" modal
* Observe the warnings in the "Markers" area of RStudio 

### Describe the problem in detail

Deselecting files during a deployment does not appear to remove those files from the list of files checked for possible problems. This produces confusing warnings.

### Describe the behavior you expected

I would not expect to see warnings about `index.Rmd` because I explicitly deselected it.
