### ISSUE TITLE
Daily build: repetition of 'bibliography' lines in YAML header

### ISSUE THREAD

**Issue by florisvdh** [rstudio/rstudio#7718]
### System details

```
RStudio Edition : Desktop
RStudio Version : 1.4.774
OS Version      : Linux Mint 20 (~Ubuntu 20.04)
R Version       : 4.0.2
```

### Steps to reproduce the problem

Visual markdown editor: insert several citations at several places.

### Describe the problem in detail

In the YAML header, new lines are added every time, ending up with e.g.:

```yaml
bibliography: references.yaml
bibliography: references.yaml
bibliography: references.yaml
bibliography: references.yaml
```
This issue also triggers #7721

### Describe the behavior you expected

The bibliography key should appear only once.

- [X] I have read the guide to submitting good bug reports at https://github.com/rstudio/rstudio/wiki/Writing-Good-Bug-Reports . 
- [X] I have installed the latest version of RStudio and confirmed that the issue still persists.
- [X] If I am reporting a RStudio crash, I have included a diagnostics report. https://support.rstudio.com/hc/en-us/articles/200321257-Running-a-Diagnostics-Report
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
