### ISSUE TITLE
Allow styling in the console input

### ISSUE THREAD

**Issue by pnacht** [rstudio/rstudio#8772]
Currently, the console styling is mostly the same as that of the source panel, copying the background and (for the output) foreground colors.

However, the console's input color is seemingly controlled by the following in the .rstheme:

```css
.nocolor.ace_editor .ace_line span {
  color: #00aaff !important;
}
```

This is fine, but it means the console input isn't as expressive as the source panel (no styling for constants or symbols, for example).

![image](https://user-images.githubusercontent.com/15221358/105250895-47d09100-5b59-11eb-9b86-ee7ac340ff7a.png)

Would it be simple to simply copy all the (relevant) styling from the source panel?
