### ISSUE TITLE
Let the "Insert citation" dialog box of the visual editor evaluate expressions in `bibliography`

### ISSUE THREAD

**Issue by DaniMori** [rstudio/rstudio#9577]
I'm trying to create some automatization tools for my workmates, which are rather hesitant to automate their workflows. One of such tools is an Rmarkdown template to generate a processed dataset and document it in the same step. Due to organization and functional issues I need the documents created using the template to be in a folder structure within the Rstudio project with certain semantics, each document in its corresponding folder.

In order to reference the bibliography file from the template, I can use an expression in the `bibliography` field of the header. However, this expression is not evaluated when I want to "Insert citation" within the visual editor.

Consider the following YAML header:

```yaml
---
output: html_document
bibliography: www/references.bib
---
```

If one opens the "Insert citation" popup, the bibliography file `www/references.bib` is properly found and appears in the "Add to bibliography" dropdown menu (bottom left).

However, consider an expression in the bibliography field:

```yaml
---
output: html_document
bibliography: "`r file.path(rstudioapi::getActiveProject(), 'www/references.bib')`"
---
```

Although the document knits and pandoc can find the bibliography file and insert the references properly, when I "Insert citation" the dialog window does not show the bibliography file (or the drop-down menu at all), and "My sources" appear all empty.

I wouldn't consider this a bug, as I doubt the use case has ever been considered at all, but it would be handy if the visual editor could manage with it.

Thank you so much for everything you do for us users!
