### ISSUE TITLE
CSS diagnostics: Make warnings configurable

### ISSUE THREAD

**Issue by jarauh** [rstudio/rstudio#9721]
My CSS file has, among others, the following entry:

```css
table.dataTable tr.dtrg-group td { /* row group header, when using extension "rowGroup" */
  background-color: #B3D384;
}
```
CSS diagnostics give the following two warnings:
```
Element (table.dataTable) is overqualified, just use .dataTable without element name.
Element (tr.dtrg-group) is overqualified, just use .dtrg-group without element name.
```

This warning is wrong: If I remove the element names, the rule will not apply anymore, because DT imports CSS rules with element name and class selectors, which will then overrule a rule with class-only selector.

I consider this warning most annoying, because it affects many of my CSS rules.  For some of them, the element name is indeed superfluous, but it is tedious for me to check.

It would be good to have a way of configuring the diagnostics.  Maybe it's too much to configure it in the RStudio GUI, but maybe using a config file?

How do CSS diagnostics work? Is there a way to configure the underlying library?
